import streamlit as st
import boto3
import json
from PIL import Image
import io
import base64

st.title("Building with Bedrock")
st.subheader("Amazon Titan Image Generator v2 Demo")

# Setup Bedrock
bedrock_runtime = boto3.client(
    service_name="bedrock-runtime",
    region_name="us-east-1",
)

def generate_image(prompt):
    payload = {
        "taskType": "TEXT_IMAGE",
        "textToImageParams": {
            "text": prompt
        },
        "imageGenerationConfig": {
            "numberOfImages": 1,
            "quality": "standard",
            "height": 1024,
            "width": 1024,
            "cfgScale": 8.0,
            "seed": 0
        }
    }

    response = bedrock_runtime.invoke_model(
        modelId="amazon.titan-image-generator-v2:0",
        body=json.dumps(payload),
        contentType="application/json",
        accept="application/json"
    )

    response_body = json.loads(response["body"].read())
    return response_body["images"][0]


    return image_base64


def base64_to_pil(base64_string):
    imgdata = base64.b64decode(base64_string)
    return Image.open(io.BytesIO(imgdata))


# UI
prompt = st.text_input("Enter prompt")

if st.button("Generate Image"):
    if not prompt:
        st.warning("Please enter a prompt")
    else:
        with st.spinner("Generating image..."):
            image_base64 = generate_image(prompt)
            image = base64_to_pil(image_base64)
            st.image(image, caption="Generated by Amazon Titan v2")

